### ISSUE TITLE
request for adding as collaborator

### ISSUE THREAD

**Issue by nr072** [sotm-asia/sotm-asia-2019-website#1]
Hi, this is Nafiur Rahman. We are from OpenStreetMap Bangladesh, and we will working on the State of the Map Asia 2019 website. Kindly add us as collaborators. Our usernames are as follow:
@nr072
@anikdas012
@fazlerabbi37
@RajibChanda
@tasauf1980

**Comment by maning** [comment]
Done, please check your inbox.

![screen shot 2019-01-09 at 22 30 05](https://user-images.githubusercontent.com/353700/50905607-27e04000-145e-11e9-859a-13d6d954694d.png)
