### ISSUE TITLE
Add youtube link 

### ISSUE THREAD

**Issue by naveenpf** [sotm-asia/sotm-asia-2019-website#3]
https://www.youtube.com/channel/UCR7PMzU0l__u8Pt73QyHWAQ

![image](https://user-images.githubusercontent.com/12662835/64587130-f1c3d900-d3bb-11e9-80a1-d0eab196559e.png)

**Comment by nr072** [comment]
Resolved by https://github.com/sotm-asia/sotm-asia-2019-website/commit/31a121f67d202d267df8360b557b8b12b9a93f86.
